### ISSUE TITLE
Fatal error if logging in with incorrect username/password

### ISSUE THREAD

**Issue by tylerjohnsondesign** [builtmighty/builtmighty-kit#18]
Example of error:

```
PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /www/blendlabsrx_531/public/wp-content/plugins/builtmighty-kit/classes/security/class-lockdown-log.php:60
Stack trace:
#0 /www/blendlabsrx_531/public/wp-includes/class-wp-hook.php(326): BuiltMightyKit\Security\builtLockdownLog->log('developers@buil...')
#1 /www/blendlabsrx_531/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /www/blendlabsrx_531/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /www/blendlabsrx_531/public/wp-includes/pluggable.php(643): do_action('wp_login_failed', 'developers@buil...', Object(WP_Error))
#4 /www/blendlabsrx_531/public/wp-includes/user.php(106): wp_authenticate('developers@buil...', 'edz*jgp0qcb3vhp...')
#5 /www/blendlabsrx_531/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(990): wp_signon(Array, true)
#6 /www/blendlabsrx_531/public/wp-includes/class-wp-hook.php(324): WC_Form_Handler::process_l" while reading response header from upstream, client: 24.208.160.185, server: blendlabsrx.com, request: "POST /my-account/?action=login HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-blendlabsrx.sock:", host: "blendlabsrx.com:64419", referrer: "https://blendlabsrx.com/my-account/?action=login"
```

**Comment by tylerjohnsondesign** [comment]
Closed in rc/2.1.0
